version: '3.8'

services:
  vinylvault:
    build: .
    ports:
      - "8181:5000"
    volumes:
      # Persist database and cache
      - ./cache:/app/cache
      # Mount logs
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('http://localhost:5000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - vinylvault
  #   restart: unless-stopped

volumes:
  cache:
  logs: